application:
  name: challengePinApp

spring:
  r2dbc:
    url: r2dbc:mysql://${HOST}:3306
    name: ${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    #aca se pueden setear el pull de conexiones de ser necesario
  data:
    r2dbc:
      repositories:
        enabled: true

spring-doc:
  swagger-ui:
    enabled: true
    path: /