application:
  name: challengePinApp

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306
    name: pinApp
    username: root
    password: fabri
  data:
    r2dbc:
      repositories:
        enabled: true
